#!/usr/bin/env node
// Copies the parts of KaiLARP-core that the Sandbox must not fork by hand:
// the injected shim, the device profile, the capability table and the
// permission map. Writes src/core/generated.ts.
//
//   node scripts/sync-core.mjs [--core <path>]
//
// This is a *generation* step, not a runtime dependency: the Sandbox never
// imports KaiLARP-core at run time, so the app can be built on a machine that
// only has this repository plus a checked-in generated.ts.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { spawnSync } from 'node:child_process';

const here = path.dirname(fileURLToPath(import.meta.url));
const sandbox = path.resolve(here, '..');
const coreArg = process.argv.includes('--core') ? process.argv[process.argv.indexOf('--core') + 1] : null;
const core = coreArg ? path.resolve(coreArg) : path.resolve(sandbox, '..', 'KaiLARP-core');

if (!fs.existsSync(path.join(core, 'src', 'capabilities.js'))) {
  console.error(`sync-core: no KaiLARP-core at ${core}`);
  console.error('pass --core <path> or check out KaiLARP-core next to KaiLARP-Sandbox');
  process.exit(1);
}

const load = (rel) => import(pathToFileURL(path.join(core, rel)).href);
const { BASE_CAPABILITIES } = await load('src/capabilities.js');
const { F491H, deviceBootConfig } = await load('src/device.js');
const { PERMISSION_CAPABILITY_MAP } = await load('src/manifest.js');

const shim = fs.readFileSync(path.join(core, 'src', 'shim.js'), 'utf8');
const demoUpdate = fs.readFileSync(path.join(core, 'fixtures', 'apps', 'demo', 'update.webapp'), 'utf8');
const demoZip = fs.readFileSync(path.join(core, 'fixtures', 'apps', 'demo', 'application.zip')).toString('base64');

let revision = 'unknown';
try {
  const r = spawnSync('git', ['-C', core, 'rev-parse', '--short', 'HEAD'], { encoding: 'utf8' });
  if (r.status === 0) revision = r.stdout.trim();
} catch { /* not a git checkout */ }

const banner = `// GENERATED by scripts/sync-core.mjs. Do not edit by hand.
// core: ${path.relative(sandbox, core) || core}
// revision: ${revision}
// generated: ${new Date().toISOString()}
`;

const body = `${banner}
export const CORE_REVISION = ${JSON.stringify(revision)};
export const SHIM_SOURCE = ${JSON.stringify(shim)};
export const DEVICE_PROFILE = ${JSON.stringify(F491H, null, 2)} as const;
export const BOOT_DEVICE = ${JSON.stringify(deviceBootConfig(F491H), null, 2)} as const;
export const CAPABILITIES = ${JSON.stringify(BASE_CAPABILITIES, null, 2)} as const;
export const PERMISSION_CAPABILITY_MAP = ${JSON.stringify(PERMISSION_CAPABILITY_MAP, null, 2)} as const;
export const DEMO_UPDATE_WEBAPP = ${JSON.stringify(demoUpdate)};
export const DEMO_APPLICATION_ZIP_B64 = ${JSON.stringify(demoZip)};
`;

const dest = path.join(sandbox, 'src', 'core', 'generated.ts');
fs.mkdirSync(path.dirname(dest), { recursive: true });
fs.writeFileSync(dest, body);
console.log(`sync-core: wrote ${path.relative(sandbox, dest)} (${(body.length / 1024).toFixed(1)} KiB) from ${core} @ ${revision}`);
